//! Built-in metadata for well-known models.
//!
//! The catalog is a JSON file embedded at build time
//! (`catalog/models.json`, generated by `catalog/build-catalog.mjs`). It
//! serves two purposes:
//!
//! * capability lookup — context window, output limit and reasoning support
//!   of an upstream model id, so requests can be fitted to the model;
//! * default model lists — what a provider serves when its config lists no
//!   models and the upstream's own list is not (yet) known.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::OnceLock;
use switchyard_core::config::ProviderKind;
use switchyard_core::{Family, ModelInfo};

const CATALOG_JSON: &str = include_str!("../catalog/models.json");

/// One catalog record: model metadata plus where the model lives.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogEntry {
    /// Metadata keyed by the vendor's model id. `known` is always true.
    #[serde(flatten)]
    pub info: ModelInfo,
    /// Vendor family the model belongs to.
    pub family: Family,
    /// Provider kinds whose API serves this id by default. The Gemini API and
    /// Vertex AI name some models differently, so a Google model is listed
    /// only for the kinds that actually have it. Empty means "every kind of
    /// the family".
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub kinds: Vec<ProviderKind>,
}

impl CatalogEntry {
    /// Whether a provider of `kind` serves this model out of the box.
    pub fn served_by(&self, kind: ProviderKind) -> bool {
        if family_of_kind(kind) != Some(self.family) {
            return false;
        }
        self.kinds.is_empty() || self.kinds.contains(&kind)
    }
}

/// The vendor family whose catalog models a provider kind serves by default.
/// `openai-compat` and `mock` providers have no default models.
pub fn family_of_kind(kind: ProviderKind) -> Option<Family> {
    match kind {
        ProviderKind::Openai => Some(Family::Openai),
        ProviderKind::Anthropic => Some(Family::Anthropic),
        ProviderKind::Gemini | ProviderKind::Vertex => Some(Family::Google),
        ProviderKind::OpenaiCompat | ProviderKind::Mock => None,
    }
}

/// The model catalog. Obtain the embedded one with [`catalog`].
#[derive(Debug, Default)]
pub struct Catalog {
    entries: Vec<CatalogEntry>,
    exact: HashMap<String, usize>,
    lower: HashMap<String, usize>,
    /// Lower-cased id with its version suffix removed → entry, for ids the
    /// vendor also accepts without the suffix (`claude-sonnet-4-5` for
    /// `claude-sonnet-4-5-20250929`).
    undated: HashMap<String, usize>,
}

impl Catalog {
    /// Parses a catalog from JSON in the embedded file's schema.
    pub fn from_json(text: &str) -> Result<Catalog, serde_json::Error> {
        let entries: Vec<CatalogEntry> = serde_json::from_str(text)?;
        Ok(Catalog::from_entries(entries))
    }

    /// Builds a catalog, dropping entries with an empty or repeated id.
    pub fn from_entries(entries: Vec<CatalogEntry>) -> Catalog {
        let mut catalog = Catalog::default();
        for mut entry in entries {
            entry.info.id = entry.info.id.trim().to_string();
            let lower = entry.info.id.to_lowercase();
            if lower.is_empty() || catalog.lower.contains_key(&lower) {
                continue;
            }
            entry.info.known = true;
            let index = catalog.entries.len();
            catalog.exact.insert(entry.info.id.clone(), index);
            catalog.lower.insert(lower, index);
            catalog.entries.push(entry);
        }
        for (index, entry) in catalog.entries.iter().enumerate() {
            if let Some(base) = strip_version_suffix(&entry.info.id) {
                let base = base.to_lowercase();
                if !catalog.lower.contains_key(&base) {
                    catalog.undated.entry(base).or_insert(index);
                }
            }
        }
        catalog
    }

    /// Every entry, in file order.
    pub fn entries(&self) -> &[CatalogEntry] {
        &self.entries
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Metadata for a model id. See [`Catalog::lookup_entry`] for the
    /// matching rules. The returned entry has `known = true` and carries the
    /// catalog's id, which may differ from `id` in case or version suffix.
    pub fn lookup(&self, id: &str) -> Option<&ModelInfo> {
        self.lookup_entry(id).map(|e| &e.info)
    }

    /// Finds the entry for a model id, trying in order:
    ///
    /// 1. the exact id;
    /// 2. the id ignoring case;
    /// 3. the id with a trailing date or version suffix removed
    ///    (`-20250929`, `-2025-08-07`, `-latest`, `-001`);
    /// 4. the id with a leading `models/` removed (Gemini resource names),
    ///    then matched by the rules above;
    /// 5. a catalog id that equals `id` once *its* suffix is removed, so the
    ///    undated alias `claude-sonnet-4-5` finds `claude-sonnet-4-5-20250929`.
    pub fn lookup_entry(&self, id: &str) -> Option<&CatalogEntry> {
        let id = id.trim();
        if id.is_empty() {
            return None;
        }
        self.find(id)
            .or_else(|| strip_version_suffix(id).and_then(|base| self.find(base)))
            .or_else(|| {
                let rest = strip_models_prefix(id)?;
                self.lookup_entry(rest)
            })
            .or_else(|| {
                let index = *self.undated.get(&id.to_lowercase())?;
                self.entries.get(index)
            })
    }

    fn find(&self, id: &str) -> Option<&CatalogEntry> {
        let index = self
            .exact
            .get(id)
            .or_else(|| self.lower.get(&id.to_lowercase()))?;
        self.entries.get(*index)
    }

    /// The models a provider of `kind` serves when nothing else is known:
    /// `openai` → the OpenAI family, `anthropic` → Anthropic, `gemini` and
    /// `vertex` → the Google models available on that API. Other kinds have
    /// no defaults.
    pub fn models_for_kind(&self, kind: ProviderKind) -> Vec<&ModelInfo> {
        self.entries
            .iter()
            .filter(|e| e.served_by(kind))
            .map(|e| &e.info)
            .collect()
    }

    /// Every model of a vendor family.
    pub fn models_for_family(&self, family: Family) -> Vec<&ModelInfo> {
        self.entries
            .iter()
            .filter(|e| e.family == family)
            .map(|e| &e.info)
            .collect()
    }
}

/// The embedded catalog.
pub fn catalog() -> &'static Catalog {
    static CATALOG: OnceLock<Catalog> = OnceLock::new();
    CATALOG.get_or_init(|| match Catalog::from_json(CATALOG_JSON) {
        Ok(catalog) => catalog,
        Err(error) => {
            // The file is generated and covered by tests; this cannot happen
            // in a released build. Degrade to "no metadata" rather than panic.
            tracing::error!(%error, "embedded model catalog is invalid; continuing without it");
            Catalog::default()
        }
    })
}

fn strip_models_prefix(id: &str) -> Option<&str> {
    let head = id.get(..7)?;
    if head.eq_ignore_ascii_case("models/") {
        id.get(7..).filter(|rest| !rest.is_empty())
    } else {
        None
    }
}

/// Removes one trailing date or version marker from a model id:
/// `-YYYY-MM-DD`, `-YYYYMMDD`, a three-digit revision (`-001`) or `-latest`.
/// Returns `None` when the id has no such suffix (or would become empty).
pub fn strip_version_suffix(id: &str) -> Option<&str> {
    let bytes = id.as_bytes();
    let digits = |range: std::ops::Range<usize>| bytes[range].iter().all(u8::is_ascii_digit);
    let cut = |suffix_len: usize| -> Option<usize> {
        let start = bytes.len().checked_sub(suffix_len)?;
        (start > 0 && bytes[start] == b'-').then_some(start)
    };

    // -YYYY-MM-DD
    if let Some(start) = cut(11)
        && digits(start + 1..start + 5)
        && bytes[start + 5] == b'-'
        && digits(start + 6..start + 8)
        && bytes[start + 8] == b'-'
        && digits(start + 9..start + 11)
    {
        return id.get(..start);
    }
    // -YYYYMMDD
    if let Some(start) = cut(9)
        && digits(start + 1..start + 9)
    {
        return id.get(..start);
    }
    // -NNN
    if let Some(start) = cut(4)
        && digits(start + 1..start + 4)
    {
        return id.get(..start);
    }
    // -latest
    if let Some(start) = cut(7)
        && id
            .get(start + 1..)
            .is_some_and(|s| s.eq_ignore_ascii_case("latest"))
    {
        return id.get(..start);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;
    use switchyard_core::Effort;
    use switchyard_core::reasoning::ThinkingSupport;

    #[test]
    fn embedded_catalog_parses_and_is_consistent() {
        let parsed = Catalog::from_json(CATALOG_JSON).expect("embedded catalog must parse");
        let raw: Vec<serde_json::Value> = serde_json::from_str(CATALOG_JSON).unwrap();
        assert_eq!(
            parsed.len(),
            raw.len(),
            "no entry may be dropped as a duplicate"
        );
        assert!(parsed.len() >= 40);
        for entry in parsed.entries() {
            assert!(entry.info.known, "{} must be known", entry.info.id);
            assert!(!entry.info.id.is_empty());
            assert!(entry.info.owned_by.is_some(), "{}", entry.info.id);
            assert!(!entry.kinds.is_empty(), "{}", entry.info.id);
            for kind in &entry.kinds {
                assert_eq!(
                    family_of_kind(*kind),
                    Some(entry.family),
                    "{}",
                    entry.info.id
                );
            }
            if let Some(t) = &entry.info.thinking {
                assert!(
                    t.has_range() || t.has_levels(),
                    "{} has an empty thinking block",
                    entry.info.id
                );
                assert!(t.max == 0 || t.min <= t.max, "{}", entry.info.id);
            }
        }
    }

    #[test]
    fn catalog_contains_only_the_three_api_families() {
        let c = catalog();
        assert!(!c.models_for_family(Family::Openai).is_empty());
        assert!(!c.models_for_family(Family::Anthropic).is_empty());
        assert!(!c.models_for_family(Family::Google).is_empty());
        for entry in c.entries() {
            let owner = entry.info.owned_by.as_deref().unwrap_or_default();
            assert!(
                matches!(owner, "openai" | "anthropic" | "google"),
                "unexpected owner {owner} for {}",
                entry.info.id
            );
        }
        // Subscription-client-only and predict-only models are not included.
        assert!(c.lookup("codex-auto-review").is_none());
        assert!(c.lookup("imagen-4.0-generate-001").is_none());
        assert!(c.lookup("kimi-k2").is_none());
    }

    #[test]
    fn exact_lookup_returns_normalised_fields() {
        let m = catalog().lookup("claude-sonnet-4-5-20250929").unwrap();
        assert_eq!(m.id, "claude-sonnet-4-5-20250929");
        assert_eq!(m.owned_by.as_deref(), Some("anthropic"));
        assert_eq!(m.context_window, Some(200_000));
        assert_eq!(m.max_output_tokens, Some(64_000));
        assert_eq!(
            m.thinking,
            Some(ThinkingSupport {
                min: 1024,
                max: 128_000,
                zero_allowed: true,
                dynamic_allowed: false,
                levels: vec![],
            })
        );
        assert!(m.known);

        let g = catalog().lookup("gemini-2.5-pro").unwrap();
        assert_eq!(g.context_window, Some(1_048_576));
        assert_eq!(g.max_output_tokens, Some(65_536));
        let t = g.thinking.as_ref().unwrap();
        assert_eq!(
            (t.min, t.max, t.zero_allowed, t.dynamic_allowed),
            (128, 32_768, false, true)
        );

        let o = catalog().lookup("gpt-5.5").unwrap();
        assert_eq!(
            o.thinking.as_ref().unwrap().levels,
            vec![Effort::Low, Effort::Medium, Effort::High, Effort::Xhigh]
        );
    }

    #[test]
    fn model_without_thinking_is_known_and_unsupported() {
        let m = catalog().lookup("claude-3-5-haiku-20241022").unwrap();
        assert!(m.known);
        assert!(m.thinking.is_none());
        assert!(matches!(
            m.thinking_caps(),
            switchyard_core::ModelThinking::Unsupported
        ));
    }

    #[test]
    fn lookup_ignores_case() {
        assert_eq!(catalog().lookup("GPT-5.5").unwrap().id, "gpt-5.5");
        assert_eq!(
            catalog().lookup(" Gemini-2.5-Flash ").unwrap().id,
            "gemini-2.5-flash"
        );
    }

    #[test]
    fn lookup_strips_date_and_version_suffixes() {
        let c = catalog();
        assert_eq!(c.lookup("gpt-5.5-2026-04-23").unwrap().id, "gpt-5.5");
        assert_eq!(
            c.lookup("claude-opus-4-6-20260205").unwrap().id,
            "claude-opus-4-6"
        );
        assert_eq!(
            c.lookup("gemini-2.5-flash-001").unwrap().id,
            "gemini-2.5-flash"
        );
        assert_eq!(
            c.lookup("gemini-2.5-pro-latest").unwrap().id,
            "gemini-2.5-pro"
        );
        assert_eq!(
            c.lookup("GEMINI-2.5-PRO-LATEST").unwrap().id,
            "gemini-2.5-pro"
        );
    }

    #[test]
    fn lookup_strips_models_prefix() {
        let c = catalog();
        assert_eq!(
            c.lookup("models/gemini-2.5-pro").unwrap().id,
            "gemini-2.5-pro"
        );
        assert_eq!(
            c.lookup("models/gemini-2.5-flash-001").unwrap().id,
            "gemini-2.5-flash"
        );
        assert!(c.lookup("models/").is_none());
    }

    #[test]
    fn undated_alias_finds_dated_entry() {
        let c = catalog();
        assert_eq!(
            c.lookup("claude-sonnet-4-5").unwrap().id,
            "claude-sonnet-4-5-20250929"
        );
        assert_eq!(
            c.lookup("claude-opus-4-5").unwrap().id,
            "claude-opus-4-5-20251101"
        );
        // An exact entry is never shadowed by a dated sibling.
        assert_eq!(c.lookup("claude-opus-4-6").unwrap().id, "claude-opus-4-6");
    }

    #[test]
    fn unknown_ids_are_not_found() {
        let c = catalog();
        assert!(c.lookup("").is_none());
        assert!(c.lookup("llama-3.3-70b").is_none());
        assert!(c.lookup("gpt-5.5-turbo").is_none());
        assert!(c.lookup("-20250929").is_none());
    }

    #[test]
    fn suffix_stripping_rules() {
        assert_eq!(strip_version_suffix("claude-x-20250929"), Some("claude-x"));
        assert_eq!(strip_version_suffix("gpt-5-2025-08-07"), Some("gpt-5"));
        assert_eq!(
            strip_version_suffix("gemini-pro-latest"),
            Some("gemini-pro")
        );
        assert_eq!(
            strip_version_suffix("gemini-pro-LATEST"),
            Some("gemini-pro")
        );
        assert_eq!(
            strip_version_suffix("imagen-generate-001"),
            Some("imagen-generate")
        );
        assert_eq!(strip_version_suffix("gpt-4-0613"), None);
        assert_eq!(strip_version_suffix("gpt-5"), None);
        assert_eq!(strip_version_suffix("model-12"), None);
        assert_eq!(strip_version_suffix("model-2025-13"), None);
        assert_eq!(strip_version_suffix("-latest"), None);
        assert_eq!(strip_version_suffix("-001"), None);
        assert_eq!(strip_version_suffix("latest"), None);
        assert_eq!(strip_version_suffix(""), None);
        // Multi-byte text never panics.
        assert_eq!(strip_version_suffix("模型-latest"), Some("模型"));
        assert_eq!(strip_version_suffix("模型模型模型"), None);
    }

    #[test]
    fn default_lists_per_kind() {
        let c = catalog();
        let ids = |kind| -> Vec<&str> {
            c.models_for_kind(kind)
                .into_iter()
                .map(|m| m.id.as_str())
                .collect()
        };
        let openai = ids(ProviderKind::Openai);
        assert!(openai.contains(&"gpt-5.5"));
        assert!(
            openai
                .iter()
                .all(|id| !id.starts_with("claude") && !id.starts_with("gemini"))
        );

        let anthropic = ids(ProviderKind::Anthropic);
        assert!(anthropic.contains(&"claude-opus-4-6"));
        assert!(anthropic.iter().all(|id| id.starts_with("claude-")));

        let gemini = ids(ProviderKind::Gemini);
        let vertex = ids(ProviderKind::Vertex);
        assert!(gemini.contains(&"gemini-2.5-pro") && vertex.contains(&"gemini-2.5-pro"));
        // The two Google APIs name the Gemini 3 models differently.
        assert!(
            gemini.contains(&"gemini-3-pro-preview") && !vertex.contains(&"gemini-3-pro-preview")
        );
        assert!(vertex.contains(&"gemini-3-pro") && !gemini.contains(&"gemini-3-pro"));
        // Everything in either list is a Google model.
        let google: Vec<&str> = c
            .models_for_family(Family::Google)
            .into_iter()
            .map(|m| m.id.as_str())
            .collect();
        assert!(
            gemini
                .iter()
                .chain(vertex.iter())
                .all(|id| google.contains(id))
        );
        assert!(
            google
                .iter()
                .all(|id| gemini.contains(id) || vertex.contains(id))
        );

        assert!(ids(ProviderKind::OpenaiCompat).is_empty());
        assert!(ids(ProviderKind::Mock).is_empty());
    }

    #[test]
    fn duplicates_and_blank_ids_are_dropped() {
        let text = r#"[
            {"id":"a","family":"openai"},
            {"id":"A","family":"anthropic"},
            {"id":"  ","family":"openai"},
            {"id":"b-20250101","family":"google","kinds":["vertex"]}
        ]"#;
        let c = Catalog::from_json(text).unwrap();
        assert_eq!(c.len(), 2);
        assert_eq!(c.lookup_entry("a").unwrap().family, Family::Openai);
        assert_eq!(c.lookup("b").unwrap().id, "b-20250101");
        // No `kinds` means every kind of the family.
        assert!(c.lookup_entry("a").unwrap().served_by(ProviderKind::Openai));
        assert!(
            !c.lookup_entry("a")
                .unwrap()
                .served_by(ProviderKind::Anthropic)
        );
        assert!(c.lookup_entry("b").unwrap().served_by(ProviderKind::Vertex));
        assert!(!c.lookup_entry("b").unwrap().served_by(ProviderKind::Gemini));
    }

    #[test]
    fn entries_serialise_in_the_file_schema() {
        let entry = catalog().lookup_entry("gemini-2.5-pro").unwrap();
        let json = serde_json::to_value(entry).unwrap();
        assert_eq!(json["id"], "gemini-2.5-pro");
        assert_eq!(json["family"], "google");
        assert_eq!(json["kinds"], serde_json::json!(["gemini", "vertex"]));
        assert_eq!(json["known"], true);
        assert_eq!(json["thinking"]["dynamic_allowed"], true);
        let back: CatalogEntry = serde_json::from_value(json).unwrap();
        assert_eq!(&back, entry);
    }
}
